#!/usr/bin/env python3
"""
Full Production Setup Script

This script will setup the entire ETF Portfolio Backtesting System for production use:
1. Test MySQL connection
2. Create database and tables
3. Insert sample data (ETFs and Portfolios)
4. Install Python dependencies
5. Configure database connection
6. Run data collection (fetch ETF prices)
7. Verify setup
8. Launch main application

Usage:
    python setup_production.py

Author: ETF Portfolio Backtesting System
"""

import os
import sys
import subprocess
import getpass
from pathlib import Path

# Colors for output
class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    END = '\033[0m'

def print_header(message):
    """Print formatted header"""
    print(f"\n{Colors.BOLD}{Colors.CYAN}{'='*80}")
    print(f"{message.center(80)}")
    print(f"{'='*80}{Colors.END}\n")

def print_success(message):
    """Print success message"""
    print(f"{Colors.GREEN}✓ {message}{Colors.END}")

def print_error(message):
    """Print error message"""
    print(f"{Colors.RED}✗ {message}{Colors.END}")

def print_warning(message):
    """Print warning message"""
    print(f"{Colors.YELLOW}⚠ {message}{Colors.END}")

def print_info(message):
    """Print info message"""
    print(f"{Colors.CYAN}ℹ {message}{Colors.END}")

def test_mysql_connection(host, port, user, password):
    """Test MySQL connection"""
    try:
        import mysql.connector
        conn = mysql.connector.connect(
            host=host,
            port=port,
            user=user,
            password=password
        )
        conn.close()
        return True, None
    except ImportError:
        return False, "mysql-connector-python not installed. Run: pip install mysql-connector-python"
    except Exception as e:
        return False, str(e)

def run_sql_file(file_path, host, port, user, password, database=None):
    """Execute SQL file"""
    try:
        import mysql.connector

        connect_params = {
            'host': host,
            'port': port,
            'user': user,
            'password': password
        }

        if database:
            connect_params['database'] = database

        conn = mysql.connector.connect(**connect_params)
        cursor = conn.cursor()

        # Read and execute SQL file
        with open(file_path, 'r', encoding='utf-8') as f:
            sql_script = f.read()

        # Split by semicolon and execute each statement
        statements = sql_script.split(';')
        for statement in statements:
            statement = statement.strip()
            if statement:
                try:
                    cursor.execute(statement)
                except Exception as e:
                    # Some statements might fail (like DROP IF EXISTS on non-existent tables)
                    # Only show error if it's not a "doesn't exist" error
                    if "doesn't exist" not in str(e).lower():
                        print_warning(f"SQL Warning: {str(e)[:100]}")

        conn.commit()
        cursor.close()
        conn.close()
        return True, None

    except Exception as e:
        return False, str(e)

def install_dependencies():
    """Install Python dependencies"""
    try:
        print_info("Installing Python dependencies...")
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"],
            capture_output=True,
            text=True,
            timeout=300
        )

        if result.returncode == 0:
            return True, None
        else:
            return False, result.stderr

    except Exception as e:
        return False, str(e)

def create_config_file(host, port, user, password, database):
    """Create config.ini file"""
    try:
        config_content = f"""# ETF Portfolio Backtesting System Configuration
# Generated by setup_production.py

[database]
host = {host}
user = {user}
password = {password}
database = {database}
port = {port}

[application]
log_level = INFO
default_initial_capital = 100000.0
default_transaction_cost = 0.001
default_risk_free_rate = 0.02

[analytics]
default_benchmark = SPY
chart_dpi = 300

[data_collection]
default_start_date = 2009-01-01
default_end_date = 2025-12-31
max_retries = 3
"""

        with open('config.ini', 'w') as f:
            f.write(config_content)

        return True, None

    except Exception as e:
        return False, str(e)

def check_database_setup(host, port, user, password, database):
    """Verify database setup"""
    try:
        import mysql.connector

        conn = mysql.connector.connect(
            host=host,
            port=port,
            user=user,
            password=password,
            database=database
        )
        cursor = conn.cursor()

        # Check tables
        cursor.execute("SHOW TABLES")
        tables = [row[0] for row in cursor.fetchall()]

        expected_tables = ['etfs', 'daily_prices', 'portfolios', 'portfolio_etfs',
                          'backtests', 'backtest_transactions', 'backtest_portfolio_values',
                          'backtest_metrics']

        missing_tables = [t for t in expected_tables if t not in tables]

        # Check ETFs
        cursor.execute("SELECT COUNT(*) FROM etfs")
        etf_count = cursor.fetchone()[0]

        # Check price data
        cursor.execute("SELECT COUNT(*) FROM daily_prices")
        price_count = cursor.fetchone()[0]

        # Check portfolios
        cursor.execute("SELECT COUNT(*) FROM portfolios")
        portfolio_count = cursor.fetchone()[0]

        cursor.close()
        conn.close()

        return {
            'success': len(missing_tables) == 0,
            'tables': tables,
            'missing_tables': missing_tables,
            'etf_count': etf_count,
            'price_count': price_count,
            'portfolio_count': portfolio_count
        }

    except Exception as e:
        return {'success': False, 'error': str(e)}

def main():
    """Main setup process"""
    print_header("ETF PORTFOLIO BACKTESTING SYSTEM")
    print_header("FULL PRODUCTION SETUP")

    print(f"\n{Colors.BOLD}This script will setup the complete system for production use.{Colors.END}")
    print("\nSteps:")
    print("  1. Test MySQL connection")
    print("  2. Create database and tables")
    print("  3. Insert sample data (40 ETFs, 8 portfolios)")
    print("  4. Install Python dependencies")
    print("  5. Create configuration file")
    print("  6. Run data collection (fetch ETF prices 2009-2025)")
    print("  7. Verify setup")
    print("  8. Ready to run!")

    input(f"\n{Colors.YELLOW}Press Enter to continue...{Colors.END}")

    # =========================================================================
    # STEP 1: Get MySQL credentials
    # =========================================================================
    print_header("STEP 1: MySQL Connection Setup")

    host = input(f"{Colors.CYAN}MySQL Host [127.0.0.1]: {Colors.END}").strip() or "127.0.0.1"
    port = input(f"{Colors.CYAN}MySQL Port [3306]: {Colors.END}").strip() or "3306"
    port = int(port)
    user = input(f"{Colors.CYAN}MySQL User [root]: {Colors.END}").strip() or "root"
    password = getpass.getpass(f"{Colors.CYAN}MySQL Password: {Colors.END}")
    database = "etf_backtesting"

    print_info(f"Testing connection to {user}@{host}:{port}...")
    success, error = test_mysql_connection(host, port, user, password)

    if not success:
        print_error(f"MySQL connection failed: {error}")
        print_warning("Please check your credentials and MySQL server status")
        sys.exit(1)

    print_success("MySQL connection successful!")

    # =========================================================================
    # STEP 2: Install dependencies
    # =========================================================================
    print_header("STEP 2: Installing Python Dependencies")

    print_info("This may take a few minutes...")
    success, error = install_dependencies()

    if not success:
        print_warning("Some dependencies may have failed to install")
        print_warning(f"Error: {error}")
        print_info("Continuing anyway... You may need to install manually later")
    else:
        print_success("All dependencies installed successfully!")

    # =========================================================================
    # STEP 3: Create database and tables
    # =========================================================================
    print_header("STEP 3: Creating Database and Tables")

    sql_files = [
        ('database/01_create_database.sql', None, 'Database and tables'),
        ('database/02_insert_sample_etfs.sql', database, '40 Sample ETFs'),
        ('database/03_insert_sample_portfolios.sql', database, '8 Sample portfolios')
    ]

    for sql_file, db, description in sql_files:
        if os.path.exists(sql_file):
            print_info(f"Creating {description}...")
            success, error = run_sql_file(sql_file, host, port, user, password, db)

            if success:
                print_success(f"{description} created successfully!")
            else:
                print_error(f"Failed to create {description}: {error}")
                if "01_create_database" in sql_file:
                    print_error("Cannot continue without database. Exiting.")
                    sys.exit(1)
        else:
            print_warning(f"SQL file not found: {sql_file}")

    # =========================================================================
    # STEP 4: Create config file
    # =========================================================================
    print_header("STEP 4: Creating Configuration File")

    success, error = create_config_file(host, port, user, password, database)

    if success:
        print_success("config.ini created successfully!")
    else:
        print_warning(f"Failed to create config.ini: {error}")
        print_info("You can create it manually later")

    # =========================================================================
    # STEP 5: Verify database setup
    # =========================================================================
    print_header("STEP 5: Verifying Database Setup")

    status = check_database_setup(host, port, user, password, database)

    if status.get('success'):
        print_success("Database setup verified!")
        print(f"\n{Colors.CYAN}Database Statistics:{Colors.END}")
        print(f"  Tables: {len(status['tables'])}/8")
        print(f"  ETFs: {status['etf_count']}")
        print(f"  Price Records: {status['price_count']:,}")
        print(f"  Portfolios: {status['portfolio_count']}")

        if status['missing_tables']:
            print_warning(f"Missing tables: {', '.join(status['missing_tables'])}")
    else:
        print_error(f"Database verification failed: {status.get('error', 'Unknown error')}")

    # =========================================================================
    # STEP 6: Data collection
    # =========================================================================
    print_header("STEP 6: ETF Price Data Collection")

    if status.get('price_count', 0) > 10000:
        print_info(f"Price data already exists ({status['price_count']:,} records)")
        run_collection = input(f"{Colors.YELLOW}Re-fetch price data? This will take 10-15 minutes (y/n): {Colors.END}").strip().lower()
    else:
        run_collection = 'y'
        print_info("No price data found. Will fetch historical prices...")

    if run_collection == 'y':
        print_info("Fetching historical prices for 40+ ETFs (2009-2025)...")
        print_warning("This will take approximately 10-15 minutes")
        print_info("You can monitor progress in another terminal:")
        print(f"  {Colors.CYAN}tail -f data_collection/data_collection.log{Colors.END}")

        proceed = input(f"\n{Colors.YELLOW}Start data collection now? (y/n): {Colors.END}").strip().lower()

        if proceed == 'y':
            try:
                # Change to data_collection directory
                original_dir = os.getcwd()
                os.chdir('data_collection')

                print_info("Starting data collection...")
                result = subprocess.run(
                    [sys.executable, "data_collection.py"],
                    timeout=1200  # 20 minute timeout
                )

                os.chdir(original_dir)

                if result.returncode == 0:
                    print_success("Data collection completed!")
                else:
                    print_warning("Data collection may have encountered issues")
                    print_info("Check data_collection/data_collection.log for details")

            except subprocess.TimeoutExpired:
                print_warning("Data collection timed out (20 minutes)")
                print_info("You can run it manually later: cd data_collection && python data_collection.py")
            except Exception as e:
                print_warning(f"Data collection error: {e}")
                print_info("You can run it manually later: cd data_collection && python data_collection.py")
        else:
            print_info("Skipping data collection")
            print_warning("Run manually later: cd data_collection && python data_collection.py")

    # =========================================================================
    # FINAL VERIFICATION
    # =========================================================================
    print_header("FINAL VERIFICATION")

    final_status = check_database_setup(host, port, user, password, database)

    print(f"\n{Colors.BOLD}{Colors.GREEN}SETUP SUMMARY:{Colors.END}")
    print(f"{Colors.CYAN}{'='*80}{Colors.END}")

    if final_status.get('success'):
        print_success("Database: Ready")
        print(f"  └─ Tables: {len(final_status['tables'])}/8")
        print(f"  └─ ETFs: {final_status['etf_count']}")
        print(f"  └─ Portfolios: {final_status['portfolio_count']}")
        print(f"  └─ Price Records: {final_status['price_count']:,}")
    else:
        print_warning("Database: Needs attention")

    if os.path.exists('config.ini'):
        print_success("Configuration: config.ini created")
    else:
        print_warning("Configuration: config.ini not found")

    if final_status.get('price_count', 0) > 10000:
        print_success(f"Price Data: {final_status['price_count']:,} records loaded")
    else:
        print_warning("Price Data: Limited or no data")
        print_info("  Run: cd data_collection && python data_collection.py")

    # =========================================================================
    # READY TO RUN
    # =========================================================================
    print_header("SETUP COMPLETE!")

    print(f"\n{Colors.BOLD}{Colors.GREEN}✓ System is ready for production use!{Colors.END}\n")

    print(f"{Colors.CYAN}Next Steps:{Colors.END}")
    print(f"  1. Launch main application:")
    print(f"     {Colors.BOLD}python main.py{Colors.END}")
    print(f"\n  2. Or run analytics examples:")
    print(f"     {Colors.BOLD}cd analytics && python example_analytics.py{Colors.END}")
    print(f"\n  3. Or run backtesting:")
    print(f"     {Colors.BOLD}cd backtesting && python example_backtest.py{Colors.END}")

    print(f"\n{Colors.CYAN}Configuration:{Colors.END}")
    print(f"  Database: {database}")
    print(f"  Host: {host}:{port}")
    print(f"  Config: config.ini")

    print(f"\n{Colors.CYAN}Documentation:{Colors.END}")
    print(f"  Main: README.md")
    print(f"  Database: database/README.md")
    print(f"  Analytics: analytics/README.md")
    print(f"  Backtesting: backtesting/README.md")

    print(f"\n{Colors.BOLD}{Colors.CYAN}{'='*80}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.GREEN}Happy Investing! 📊🚀{Colors.END}\n")

    # Ask if user wants to launch main app
    launch = input(f"{Colors.YELLOW}Launch main application now? (y/n): {Colors.END}").strip().lower()

    if launch == 'y':
        print_info("Launching main application...")
        os.system(f"{sys.executable} main.py")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Setup interrupted by user{Colors.END}")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
